# Generated by Django 5.1.1 on 2024-09-12 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('organizations', '0001_initial'),
        ('utils', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.country', verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='event',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='published_events', to='organizations.organization', verbose_name='Organisation du publicateur'),
        ),
        migrations.AddField(
            model_name='event',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_events', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur ayant publié'),
        ),
        migrations.AddField(
            model_name='eticket',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='e_tickets', to='events.event', verbose_name='Évènement connexe'),
        ),
        migrations.AddField(
            model_name='eventhighlighting',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='highlight', to='events.event', verbose_name='Évènement connexe'),
        ),
        migrations.AddField(
            model_name='eventhighlighting',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_highlight', to='events.eventhighlightingtype', verbose_name='Type De Mise en Avant lié'),
        ),
        migrations.AddField(
            model_name='eventimage',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='events.event', verbose_name='Évènement relatif'),
        ),
        migrations.AddField(
            model_name='eventimage',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_event_images', to='organizations.organization', verbose_name='Organisateur'),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_event_types', to='organizations.organization', verbose_name='Organisateur'),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='events.eventtype', verbose_name='Catégorie parente'),
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='events.eventtype', verbose_name="Type de l'évènement"),
        ),
        migrations.AddField(
            model_name='favouriteevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adds_like_favourite', to='events.event', verbose_name='Évènement connexe'),
        ),
        migrations.AddField(
            model_name='favouriteevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_events', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur lié'),
        ),
        migrations.AddField(
            model_name='favouriteeventtype',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adds_like_favourite', to='events.eventtype', verbose_name="Type d'évènement  connexe"),
        ),
        migrations.AddField(
            model_name='favouriteeventtype',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_event_types', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur lié'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='country',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='utils.country', verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization', verbose_name='Organisation du publicateur'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='publisher',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur ayant publié'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='events.eventtype', verbose_name="Type de l'évènement"),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='events.orderitem', verbose_name='Items de la commande'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='events.event', verbose_name='Évènement connexe'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tickets', to='organizations.organization', verbose_name='Organisateur'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ordered_items', to='events.ticket', verbose_name='Ticket'),
        ),
        migrations.AddField(
            model_name='eticket',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='e_tickets', to='events.ticket', verbose_name='Ticket connexe'),
        ),
        migrations.AddField(
            model_name='ticketcategory',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_categories', to='events.event', verbose_name='Évènement connexe'),
        ),
        migrations.AddField(
            model_name='ticketcategory',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_ticket_categories', to='organizations.organization', verbose_name='Organisateur'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tickets', to='events.ticketcategory', verbose_name='Catégorie du ticket'),
        ),
        migrations.AddField(
            model_name='ticketcategoryfeature',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_ticket_category_features', to='organizations.organization', verbose_name='Organisateur'),
        ),
        migrations.AddField(
            model_name='ticketcategory',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='ticket_categories', to='events.ticketcategoryfeature'),
        ),
        migrations.AlterUniqueTogether(
            name='eventtype',
            unique_together={('name', 'description')},
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('name', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='favouriteevent',
            unique_together={('user', 'event')},
        ),
        migrations.AlterUniqueTogether(
            name='favouriteeventtype',
            unique_together={('user', 'event_type')},
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('name', 'category')},
        ),
    ]
