# Generated by Django 5.1.1 on 2024-10-07 06:47

import apps.utils.utils.codes.utils
import datetime
import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtype',
            name='organization',
        ),
        migrations.AlterField(
            model_name='event',
            name='cover_image',
            field=models.ImageField(upload_to=apps.utils.utils.codes.utils._upload_to, verbose_name="Cover officiel de l' évènement"),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(verbose_name="Date à laquelle aura lieu l' évènement "),
        ),
        migrations.AlterField(
            model_name='event',
            name='hour',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name="Heure à laquelle aura lieu l' évènement "),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326, verbose_name="Lieu de l' évènement "),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='events.eventtype', verbose_name="Type de l' évènement"),
        ),
        migrations.AlterField(
            model_name='eventhighlighting',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date(2024, 10, 14), verbose_name='Date de fin de validité'),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='cover_image',
            field=models.TextField(max_length=100, verbose_name="Cover officiel de l' évènement"),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='date',
            field=models.DateField(verbose_name="Date à laquelle aura lieu l' évènement "),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='hour',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name="Heure à laquelle aura lieu l' évènement "),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326, verbose_name="Lieu de l' évènement "),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='events.eventtype', verbose_name="Type de l' évènement"),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 7, 12, 47, 39, 895300), verbose_name='Date de fin de validité'),
        ),
    ]
