# Generated by Django 5.1.1 on 2024-10-21 10:59

import apps.users.models.utils
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_eventtype_organization_and_more'),
        ('organizations', '0003_historicalorganization_percentage_if_discounted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='applied_percentage',
            field=models.FloatField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='has_been_discounted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order', to='events.orderitem', verbose_name='Item de la commande'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='potential_discount_data',
            field=models.JSONField(default=apps.users.models.utils.get_transaction_default_coupon_metadata, verbose_name="Information d' une potentielle réduction"),
        ),
        migrations.AlterField(
            model_name='eticket',
            name='expiration_date',
            field=models.DateTimeField(blank=True, verbose_name="Date d' expiration"),
        ),
        migrations.AlterField(
            model_name='eticket',
            name='is_downloaded',
            field=models.BooleanField(default=False, verbose_name='Désigne si le ticket a été téléchargé'),
        ),
        migrations.AlterField(
            model_name='eticket',
            name='name',
            field=models.CharField(blank=True, max_length=220, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='eticket',
            name='qr_code_data',
            field=models.CharField(blank=True, max_length=512, verbose_name='Données de QR code'),
        ),
        migrations.AlterField(
            model_name='eticket',
            name='related_order_id',
            field=models.CharField(max_length=120, verbose_name='Commende relative'),
        ),
        migrations.AlterField(
            model_name='eticket',
            name='secret_key',
            field=models.BinaryField(blank=True, editable=True, max_length=256, verbose_name='Clé secrete'),
        ),
        migrations.AlterField(
            model_name='eticket',
            name='secret_phrase',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Secret'),
        ),
        migrations.AlterField(
            model_name='eventhighlighting',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date(2024, 10, 28), verbose_name='Date de fin de validité'),
        ),
        migrations.AlterField(
            model_name='eventhighlightingtype',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=15, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='orders', to='events.orderitem', verbose_name='Items de la commande'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 21, 16, 59, 11, 193842), verbose_name='Date de fin de validité'),
        ),
        migrations.AlterField(
            model_name='ticketcategory',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='ticket_categories', to='events.ticketcategoryfeature', verbose_name='Avantages'),
        ),
        migrations.AlterField(
            model_name='ticketcategory',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_ticket_categories', to='organizations.organization', verbose_name='Organisation'),
        ),
    ]
