# Generated by Django 5.1.1 on 2024-10-21 10:59

from django.db import migrations, transaction


@transaction.atomic
def upgrade_orders_records(apps, schema_editor):
    OrderModel = apps.get_model('events', 'Order')

    # Perform your desired modifications here
    orders = OrderModel.objects.all()

    for order in orders:
        order_item = order.items.all().last()
        order.item_id = order_item.pk
        order.save(update_fields=['item_id'])


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0004_order_applied_percentage_order_has_been_discounted_and_more'),
    ]

    operations = [
        migrations.RunPython(upgrade_orders_records)
    ]
