# Generated by Django 5.1.1 on 2024-10-21 11:03

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20241021_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order', to='events.orderitem', verbose_name='Item de la commande'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 21, 17, 3, 33, 360762), verbose_name='Date de fin de validité'),
        ),
    ]
