# Generated by Django 5.1.4 on 2024-12-29 20:00

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_order_items_alter_order_item_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventtype',
            options={'verbose_name': "Type d' évènement", 'verbose_name_plural': "Types d' évènement"},
        ),
        migrations.RenameField(
            model_name='eticket',
            old_name='related_order_id',
            new_name='old_related_order_id',
        ),
        migrations.AddField(
            model_name='eticket',
            name='related_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='related_e_tickets', to='events.order', verbose_name='Commende relative'),
        ),
        migrations.AlterField(
            model_name='eventhighlighting',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 1, 5), verbose_name='Date de fin de validité'),
        ),
        migrations.AlterField(
            model_name='order',
            name='applied_percentage',
            field=models.FloatField(default=False, verbose_name='Pourcentage appliqué'),
        ),
        migrations.AlterField(
            model_name='order',
            name='has_been_discounted',
            field=models.BooleanField(default=False, verbose_name="Désigne si la commande est objet d' une réduction."),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_income_distributed',
            field=models.BooleanField(default=False, verbose_name='Désigne si les revenu ont été distribués'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 30, 3, 0, 24, 824989), verbose_name='Date de fin de validité'),
        ),
    ]
