# Generated by Django 5.1.4 on 2024-12-29 15:23

from django.db import migrations
from django.db.models import UUIDField
from django.db.models.functions import Cast


def forwards_func(apps, schema_editor):
    ETicketModel = apps.get_model('events', 'ETicket')
    db_alias = schema_editor.connection.alias
    ETicketModel.objects.using(db_alias).update(related_order_id=Cast('old_related_order_id', UUIDField()))


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0007_alter_eventtype_options_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards_func)
    ]
