# Generated by Django 5.1.4 on 2024-12-29 18:04

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0008_auto_20241229_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eticket',
            name='old_related_order_id',
        ),
        migrations.AlterField(
            model_name='eticket',
            name='related_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='related_e_tickets',
                                    to='events.order', verbose_name='Commende relative'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 30, 1, 3, 46, 149489),
                                       verbose_name='Date de fin de validité'),
        ),
    ]
