# Generated by Django 5.1.6 on 2025-02-25 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_remove_eticket_old_related_order_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventhighlighting",
            name="end_date",
            field=models.DateField(
                blank=True,
                default=datetime.date(2025, 3, 4),
                verbose_name="Date de fin de validité",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="expiry_date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 2, 25, 21, 0, 52, 468222),
                verbose_name="Date de fin de validité",
            ),
        ),
    ]
