# Generated by Django 5.1.6 on 2025-02-25 23:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_alter_eventhighlighting_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="expiry_date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 2, 26, 6, 47, 45, 921419),
                verbose_name="Date de fin de validité",
            ),
        ),
    ]
