# Generated by Django 5.1.7 on 2025-03-09 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_ticket_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventhighlighting',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 3, 16), verbose_name='Date de fin de validité'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 10, 0, 25, 3, 320348), verbose_name='Date de fin de validité'),
        ),
    ]
