# Generated by Django 5.1.7 on 2025-03-09 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_eventhighlighting_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 10, 1, 49, 7, 203331), verbose_name='Date de fin de validité'),
        ),
    ]
