# Generated by Django 5.2.1 on 2025-05-14 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_alter_ticket_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Est privé'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Est privé'),
        ),
        migrations.AlterField(
            model_name='eventhighlighting',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 5, 21), verbose_name='Date de fin de validité'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 14, 15, 13, 15, 446274), verbose_name='Date de fin de validité'),
        ),
    ]
