# Generated by Django 5.1.4 on 2025-05-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0013_alter_ticket_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_pseudo_anonymous',
            field=models.BooleanField(default=False, verbose_name="Désigne l'achat est pseudo anonyme"),
        ),
    ]
