# Generated by Django 5.2.1 on 2025-05-14 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_event_private_historicalevent_private_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participant_limit',
            field=models.IntegerField(blank=True, default=15, verbose_name='Limite de participants'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='participant_limit',
            field=models.IntegerField(blank=True, default=15, verbose_name='Limite de participants'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 14, 15, 20, 7, 126742), verbose_name='Date de fin de validité'),
        ),
    ]
