# Generated by Django 5.2.1 on 2025-05-15 17:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_event_participant_limit_and_more'),
        ('utils', '0003_alter_variable_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('private', False), ('participant_count__lte', models.F('participant_limit')), _connector='OR'), name='private_event_participant_limit'),
        ),
    ]
