# Generated by Django 5.2.4 on 2025-07-10 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_order_is_pseudo_anonymous'),
        ('events', '0016_alter_eventhighlighting_end_date_and_more'),
    ]

    operations = [
    ]
