# Generated by Django 5.2.1 on 2025-10-28 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_merge_20250710_2156'),
        ('events', '0017_sponsor_order_is_pseudo_anonymous_and_more'),
    ]

    operations = [
    ]
