# Generated by Django 5.2.1 on 2025-10-29 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_merge_20251028_2033'),
        ('events', '0019_event_created_by_super_seller_and_more'),
    ]

    operations = [
    ]
