# Generated by Django 5.2.1 on 2025-11-07 07:08

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_alter_eventhighlighting_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventhighlighting',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 11, 14), verbose_name='Date de fin de validité'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 7, 14, 8, 0, 666737), verbose_name='Date de fin de validité'),
        ),
        migrations.CreateModel(
            name='TicketDelivery',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name="Date d' ajout")),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('active', models.BooleanField(default=True, verbose_name="Désigne si l' instance est active")),
                ('recipient_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email destinataire')),
                ('recipient_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone destinataire')),
                ('recipient_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom destinataire')),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('SMS', 'SMS')], max_length=20, verbose_name="Canal d'envoi")),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SENDING', "En cours d'envoi"), ('SENT', 'Envoyé avec succès'), ('FAILED', 'Échec'), ('RETRY', 'En attente de nouvel essai')], default='PENDING', max_length=20, verbose_name='État')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de tentatives')),
                ('max_retry_count', models.PositiveIntegerField(default=3, verbose_name='Nombre maximum de tentatives')),
                ('next_retry_at', models.DateTimeField(blank=True, null=True, verbose_name='Prochaine tentative à')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Envoyé le')),
                ('failed_at', models.DateTimeField(blank=True, null=True, verbose_name='Échoué le')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name="Message d'erreur")),
                ('delivery_logs', models.JSONField(default=list, help_text='Historique détaillé de toutes les tentatives', verbose_name="Logs d'envoi")),
                ('provider_response', models.JSONField(blank=True, help_text="Réponse complète du service d'envoi (Courier, etc.)", null=True, verbose_name='Réponse du fournisseur')),
                ('eticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='events.eticket', verbose_name='E-Ticket')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_deliveries', to='events.order', verbose_name='Commande')),
            ],
            options={
                'verbose_name': 'Envoi de ticket',
                'verbose_name_plural': 'Envois de tickets',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['status', '-timestamp'], name='events_tick_status_639aac_idx'), models.Index(fields=['channel', 'status'], name='events_tick_channel_11d76f_idx'), models.Index(fields=['order', '-timestamp'], name='events_tick_order_i_cc2280_idx'), models.Index(fields=['eticket'], name='events_tick_eticket_35bd7d_idx'), models.Index(fields=['next_retry_at'], name='idx_next_retry')],
            },
        ),
    ]
