# Generated by Django 5.2.1 on 2025-11-07 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_alter_eventhighlighting_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 7, 23, 3, 56, 749283), verbose_name='Date de fin de validité'),
        ),
    ]
