# Generated by Django 5.2.1 on 2025-11-09 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_alter_ticket_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventhighlighting',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 11, 16), verbose_name='Date de fin de validité'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 10, 1, 31, 13, 237180), verbose_name='Date de fin de validité'),
        ),
    ]
