# Generated by Django 5.2.1 on 2025-11-15 07:55

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_alter_eventhighlighting_end_date_and_more'),
        ('organizations', '0005_historicalorganization_organization_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventhighlighting',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 11, 22), verbose_name='Date de fin de validité'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 15, 14, 55, 35, 527370), verbose_name='Date de fin de validité'),
        ),
        migrations.CreateModel(
            name='EventCommissionOffer',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name="Date d' ajout")),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('active', models.BooleanField(default=True, verbose_name="Désigne si l' instance est active")),
                ('commission_percentage', models.DecimalField(decimal_places=2, help_text='Commission offerte aux super-vendeurs (minimum 10%)', max_digits=5, validators=[django.core.validators.MinValueValidator(10.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Pourcentage de commission (%)')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'En pause'), ('EXPIRED', 'Expirée'), ('CANCELLED', 'Annulée')], default='ACTIVE', max_length=20, verbose_name="Statut de l'offre")),
                ('description', models.TextField(blank=True, help_text='Détails supplémentaires sur cette offre', verbose_name='Description')),
                ('valid_until', models.DateTimeField(blank=True, help_text="Date limite de validité de l'offre", null=True, verbose_name="Valide jusqu'au")),
                ('total_accepted', models.IntegerField(default=0, help_text='Nombre de super-vendeurs ayant accepté', verbose_name="Nombre d'acceptations")),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Informations supplémentaires', verbose_name='Métadonnées')),
                ('event', models.OneToOneField(help_text="L'événement concerné par cette offre", on_delete=django.db.models.deletion.CASCADE, related_name='commission_offer', to='events.event', verbose_name='Événement')),
                ('organization', models.ForeignKey(help_text='Organisation qui propose cette commission', on_delete=django.db.models.deletion.CASCADE, related_name='commission_offers', to='organizations.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Offre de Commission',
                'verbose_name_plural': 'Offres de Commission',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SuperSellerOfferAcceptance',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name="Date d' ajout")),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('active', models.BooleanField(default=True, verbose_name="Désigne si l' instance est active")),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('ACCEPTED', 'Acceptée'), ('REJECTED', 'Rejetée'), ('CANCELLED', 'Annulée')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('seller_commission_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Pourcentage de commission offert aux vendeurs par le super-vendeur', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Commission vendeur (%)')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Acceptée le')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='Rejetée le')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Raison du rejet')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptances', to='events.eventcommissionoffer', verbose_name='Offre de commission')),
                ('super_seller', models.ForeignKey(help_text="Organisation super-vendeur acceptant l'offre", on_delete=django.db.models.deletion.CASCADE, related_name='offer_acceptances', to='organizations.organization', verbose_name='Super-Vendeur')),
            ],
            options={
                'verbose_name': "Acceptation d'Offre",
                'verbose_name_plural': "Acceptations d'Offres",
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='eventcommissionoffer',
            index=models.Index(fields=['event', 'status'], name='events_even_event_i_305559_idx'),
        ),
        migrations.AddIndex(
            model_name='eventcommissionoffer',
            index=models.Index(fields=['organization', 'status'], name='events_even_organiz_3c7b3e_idx'),
        ),
        migrations.AddIndex(
            model_name='eventcommissionoffer',
            index=models.Index(fields=['status', '-timestamp'], name='events_even_status_6aa289_idx'),
        ),
        migrations.AddIndex(
            model_name='supersellerofferacceptance',
            index=models.Index(fields=['super_seller', 'status'], name='events_supe_super_s_eae6af_idx'),
        ),
        migrations.AddIndex(
            model_name='supersellerofferacceptance',
            index=models.Index(fields=['offer', 'status'], name='events_supe_offer_i_d0a2d8_idx'),
        ),
        migrations.AddIndex(
            model_name='supersellerofferacceptance',
            index=models.Index(fields=['status', '-timestamp'], name='events_supe_status_8a44cc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='supersellerofferacceptance',
            unique_together={('offer', 'super_seller')},
        ),
    ]
