# Generated by Django 5.2.1 on 2025-12-01 08:58

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_alter_eventhighlighting_end_date_and_more'),
        ('organizations', '0005_historicalorganization_organization_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventhighlighting',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 12, 8), verbose_name='Date de fin de validité'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='organization_member',
            field=models.OneToOneField(blank=True, help_text="Référence au membre d'organisation (rôle SELLER)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_profile', to='organizations.organizationmembership', verbose_name="Membre d'organisation"),
        ),
        migrations.AlterField(
            model_name='seller',
            name='super_seller',
            field=models.ForeignKey(help_text='Organisation super-vendeur qui gère ce vendeur', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sellers', to='organizations.organization', verbose_name='Super-Vendeur'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='user',
            field=models.ForeignKey(help_text="L'utilisateur associé à ce vendeur", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='supersellerprofile',
            name='organization',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='super_seller_profile', to='organizations.organization', verbose_name='Organisation Super-Vendeur'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 1, 15, 58, 39, 927722), verbose_name='Date de fin de validité'),
        ),
    ]
