# -*- coding: utf-8 -*-
"""
Created on 16/10/2024

@author:
    Wesley Eliel MONTCHO, alias DevBackend7
"""
from typing import Union, Literal

from apps.xlib.enums import DISCOUNT_CONDITION_OPERATORS_ENUM, DISCOUNT_CONDITION_ENTITY_TYPES_ENUM, \
    DISCOUNT_USE_ENTITY_TYPES_ENUM, DISCOUNT_TYPES_ENUM, DISCOUNT_TARGET_TYPES_ENUM

DISCOUNT_TARGET_TYPES_ENUM_VALUES_LIKE = Literal["EVENT_HIGHLIGHTING", "SUBSCRIPTION", "TICKET"]
DISCOUNT_TYPES_ENUM_VALUES_LIKE = Literal["FREE_SHIPPING", "PERCENTAGE", "FIXED"]
DISCOUNT_USE_ENTITY_TYPES_ENUM_VALUES_LIKE = Literal["ORGANIZATION", "USER"]
DISCOUNT_CONDITION_ENTITY_TYPES_ENUM_VALUES_LIKE = Literal[
    "EVENT_HIGHLIGHTING_TYPES", "SUBSCRIPTIONS", "ORGANIZATIONS", "USERS"]
DISCOUNT_CONDITION_OPERATORS_ENUM_VALUES_LIKE = Literal["IN", "NOT_IN"]

DISCOUNT_TARGET_TYPES_ENUM_LIKE = Union[
    DISCOUNT_TARGET_TYPES_ENUM,
    DISCOUNT_TARGET_TYPES_ENUM_VALUES_LIKE
]
DISCOUNT_TYPES_ENUM_LIKE = Union[
    DISCOUNT_TYPES_ENUM,
    DISCOUNT_TYPES_ENUM_VALUES_LIKE
]
DISCOUNT_USE_ENTITY_TYPES_ENUM_LIKE = Union[
    DISCOUNT_USE_ENTITY_TYPES_ENUM,
    DISCOUNT_USE_ENTITY_TYPES_ENUM_VALUES_LIKE
]
DISCOUNT_CONDITION_ENTITY_TYPES_ENUM_LIKE = Union[
    DISCOUNT_CONDITION_ENTITY_TYPES_ENUM,
    DISCOUNT_CONDITION_ENTITY_TYPES_ENUM_VALUES_LIKE
]
DISCOUNT_CONDITION_OPERATORS_ENUM_LIKE = Union[
    DISCOUNT_CONDITION_OPERATORS_ENUM,
    DISCOUNT_CONDITION_OPERATORS_ENUM_VALUES_LIKE
]
