from enum import Enum


class BaseEnum(Enum):
    @classmethod
    def items(cls):
        return [(k.value, k.name) for k in cls]

    @classmethod
    def values(cls):
        return [k.value for k in cls]


class AppRolesEnum(BaseEnum):
    ADMIN = "ADMIN"
    STAFF = "STAFF"
    SUPPORT = "SUPPORT"
    ACCOUNTANT = "ACCOUNTANT"
    SUPER_ADMIN = "SUPER_ADMIN"
    EVENT_OWNER = "EVENT_OWNER"
    COLLABORATOR = "COLLABORATOR"
    SALES_MANAGER = "SALES_MANAGER"


class AppRolesDescriptionEnum(BaseEnum):
    ADMIN = "Administrateur"
    STAFF = "Staff"
    SUPPORT = "Support"
    ACCOUNTANT = "Comptable"
    SUPER_ADMIN = "Super Administrateur"
    EVENT_OWNER = "Propriétaire d' Évènement"
    COLLABORATOR = "Collaborateur"
    SALES_MANAGER = "Commerciaux"


class ErrorEnum(BaseEnum):
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"

    EVENT_PAST_DATE = "EVENT_PAST_DATE"
    CANNOT_ADD_EVENT_ON_PASS_DATE = "CANNOT_ADD_EVENT_ON_PASS_DATE"
    CANNOT_UPDATE_PASS_EVENT = "CANNOT_UPDATE_PASS_EVENT"
    MISSING_DEVICE_REGISTRATION_ID = "MISSING_DEVICE_REGISTRATION_ID"
    MISSING_PAGE_NUMBER = "MISSING_PAGE_NUMBER"
    MISSING_DATE = "MISSING_DATE"
    INVALID_DATE_FORMAT = "INVALID_DATE_FORMAT"
    MISSING_DATE_RANGE = "MISSING_DATE_RANGE"
    ORGANIZATION_WITH_THIS_NAME_ALREADY_EXISTS = (
        "ORGANIZATION_WITH_THIS_NAME_ALREADY_EXISTS"
    )
    INACTIVE_ORGANIZATION = "INACTIVE_ORGANIZATION"
    EMPTY_OR_NULL_ORGANIZATION_PK_IN_URL = "EMPTY_OR_NULL_ORGANIZATION_PK_IN_URL"
    SPECIFIED_PARENT_ORGANIZATION_NOT_FOUND = "SPECIFIED_PARENT_ORGANIZATION_NOT_FOUND"
    UNVERIFIED_OWNER_ACCOUNT = "UNVERIFIED_OWNER_ACCOUNT"
    INVALID_PHONE_NUMBER = "INVALID_PHONE_NUMBER"
    EMAIL_OR_PHONE_REQUIRED = "EMAIL_OR_PHONE_REQUIRED"
    USER_DOES_NOT_EXIST = "USER_DOES_NOT_EXIST"
    ALREADY_FOLLOWING_ORGANIZATION = "ALREADY_FOLLOWING_ORGANIZATION"
    DISABLE_ACCOUNT = "DISABLE_ACCOUNT"
    INCORRECT_EMAIL_OR_PASSWORD = "INCORRECT_EMAIL_OR_PASSWORD"
    INCORRECT_PHONE_OR_PASSWORD = "INCORRECT_PHONE_OR_PASSWORD"
    EMAIL_OR_PHONE_SHOULD_BE_SET = "EMAIL_OR_PHONE_SHOULD_BE_SET"
    EMAIL_OR_PHONE_ALREADY_USED = "EMAIL_OR_PHONE_ALREADY_USED"
    EMAIL_ALREADY_USED = "EMAIL_ALREADY_USED"
    PHONE_NUMBER_ALREADY_USED = "PHONE_NUMBER_ALREADY_USED"
    INSUFFICIENT_BALANCE = "INSUFFICIENT_BALANCE"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    PASSWORD_REQUIRED = "PASSWORD_REQUIRED"
    PHONE_REQUIRED = "PHONE_REQUIRED"
    SERVER_ERROR = "SERVER_ERROR"
    EVENT_UNDERGOING_VALIDATION = "EVENT_UNDERGOING_VALIDATION"
    INVALID_EVENT_DATA = "INVALID_EVENT_DATA"
    INSUFFICIENT_TICKET_QUANTITY = "INSUFFICIENT_TICKET_QUANTITY"
    INSUFFICIENT_ITEMS_FOR_ORDERING = "INSUFFICIENT_ITEMS_FOR_ORDERING"
    TICKET_ALREADY_DOWNLOADED = "TICKET_ALREADY_DOWNLOADED"
    EVENT_NOT_FOUND = "EVENT_NOT_FOUND"
    EVENT_PARTICIPANT_LIMIT_REACHED = "EVENT_PARTICIPANT_LIMIT_REACHED"
    PARTICIPANT_COUNT_EXCEEDS_LIMIT = "PARTICIPANT_COUNT_EXCEEDS_LIMIT"
    CANNOT_UPDATE_PARTICIPANT_LIMIT_WITHOUT_ACTIVE_SUBSCRIPTION = "CANNOT_UPDATE_PARTICIPANT_LIMIT_WITHOUT_ACTIVE_SUBSCRIPTION"
    EVENT_HIGHLIGHTING_TYPE_NOT_FOUND = "EVENT_HIGHLIGHTING_TYPE_NOT_FOUND"
    PROMOTION_ALREADY_EXISTS = "PROMOTION_ALREADY_EXISTS"
    ORDER_NOT_YET_PAID = "ORDER_NOT_YET_PAID"
    USER_ALREADY_MEMBER_OF_ORGANIZATION = "USER_ALREADY_MEMBER_OF_ORGANIZATION"
    USER_NOT_MEMBER_OF_ORGANIZATION = "USER_NOT_MEMBER_OF_ORGANIZATION"
    TICKET_NOT_FOUND = "TICKET_NOT_FOUND"
    COUPON_NOT_FOUND = "COUPON_NOT_FOUND"
    ORGANIZATION_NOT_FOUND = "ORGANIZATION_NOT_FOUND"
    INVALID_TICKET = "INVALID_TICKET"
    ALREADY_USED_TICKET = "ALREADY_USED_TICKET"
    PAYMENT_ALREADY_IN_PROGRESS = "PAYMENT_ALREADY_IN_PROGRESS"
    PAYMENT_TRANSACTION_NOT_FOUND = "PAYMENT_TRANSACTION_NOT_FOUND"
    WITHDRAW_TRANSACTION_NOT_FOUND = "WITHDRAW_TRANSACTION_NOT_FOUND"
    INVALID_TRANSACTION_TYPE = "INVALID_TRANSACTION_TYPE"
    GATEWAY_PAYMENT_FAILED = "GATEWAY_PAYMENT_FAILED"
    TRANSACTION_ALREADY_PAID = "TRANSACTION_ALREADY_PAID"
    TRANSACTION_INVALID_STATUS = "TRANSACTION_INVALID_STATUS"
    TRANSACTION_ALREADY_COMPLETED = "TRANSACTION_ALREADY_COMPLETED"
    RESOURCE_RESERVED_TO_ADMIN = "RESOURCE_RESERVED_TO_ADMIN"
    NO_ROLE_SPECIFIED_FOR_THE_ADMIN = "NO_ROLE_SPECIFIED_FOR_THE_ADMIN"
    MINIMAL_AMOUNT_FOR_WITHDRAW_NOT_REACHED = "MINIMAL_AMOUNT_FOR_WITHDRAW_NOT_REACHED"
    BAD_REFRESH_TOKEN = "BAD_REFRESH_TOKEN"
    NO_ACTIVE_SUBSCRIPTION = "NO_ACTIVE_SUBSCRIPTION"

    # Discount validations errors
    WRONG_MAX_USES_PER_ENTITY = "WRONG_MAX_USES_PER_ENTITY"
    WRONG_PERCENTAGE_VALUE = "WRONG_PERCENTAGE_VALUE"
    START_DATE_AFTER_END_DATE = "START_DATE_AFTER_END_DATE"
    FIXED_AMOUNT_VALUE_GREATER_THAN_MINIMAL_VALUE = (
        "FIXED_AMOUNT_VALUE_GREATER_THAN_MINIMAL_VALUE"
    )
    INCOMPATIBLE_CHOICE_BETWEEN_DISCOUNT_TYPE_AND_CONDITION_ENTITY = (
        "INCOMPATIBLE_CHOICE_BETWEEN_DISCOUNT_TYPE_AND_CONDITION_ENTITY"
    )
    DISCOUNT_CHECK_CONSUMER_ENTITY_NOT_PROVIDED = (
        "DISCOUNT_CHECK_CONSUMER_ENTITY_NOT_PROVIDED"
    )
    DISCOUNT_CHECK_DATE_VALIDITY_ERROR = "DISCOUNT_CHECK_DATE_VALIDITY_ERROR"
    DISCOUNT_CHECK_USAGE_LIMIT_VALIDATION_ERROR = (
        "DISCOUNT_CHECK_USAGE_LIMIT_VALIDATION_ERROR"
    )
    DISCOUNT_CHECK_USAGE_VALIDATION_ERROR = "DISCOUNT_CHECK_USAGE_VALIDATION_ERROR"
    DISCOUNT_CHECK_CONDITIONS_VALIDATION_ERROR = (
        "DISCOUNT_CHECK_CONDITIONS_VALIDATION_ERROR"
    )
    DISCOUNT_CHECK_MINIMAL_AMOUNT_REQUIRED_NOT_REACHED_ERROR = (
        "DISCOUNT_CHECK_MINIMAL_AMOUNT_REQUIRED_NOT_REACHED_ERROR"
    )
    DISCOUNT_FOR_TICKET_NOT_APPLICABLE_TO_ORGANIZATION = (
        "DISCOUNT_FOR_TICKET_NOT_APPLICABLE_TO_ORGANIZATION"
    )
    DISCOUNT_MAX_NUMBER_OF_COUPON_REACHED = "DISCOUNT_MAX_NUMBER_OF_COUPON_REACHED"
    YOUR_ORGANIZATION_IS_NOT_CREATOR_OF_THIS_DISCOUNT = (
        "YOUR_ORGANIZATION_IS_NOT_CREATOR_OF_THIS_DISCOUNT"
    )
    COUPON_WITH_THIS_CODE_ALREADY_EXISTS = "COUPON_WITH_THIS_CODE_ALREADY_EXISTS"
    APP_ROLE_DOES_NOT_EXIST = "APP_ROLE_DOES_NOT_EXIST"

    # Chat Rooms
    CHAT_ROOM_NOT_FOUND = "CHAT_ROOM_NOT_FOUND"
    CHAT_ROOM_SUBSCRIPTION_NOT_FOUND = "CHAT_ROOM_SUBSCRIPTION_NOT_FOUND"
    CHAT_ROOM_ALREADY_EXISTS = "CHAT_ROOM_ALREADY_EXISTS"
    USER_NOT_MEMBER_OF_CHAT_ROOM = "USER_NOT_MEMBER_OF_CHAT_ROOM"
    USER_ALREADY_MEMBER_OF_CHAT_ROOM = "USER_ALREADY_MEMBER_OF_CHAT_ROOM"
    INVALID_CHAT_ROOM_TYPE = "INVALID_CHAT_ROOM_TYPE"
    INVALID_CHAT_ROOM_VISIBILITY = "INVALID_CHAT_ROOM_VISIBILITY"
    INVALID_CHAT_ROOM_MEMBER_TYPE = "INVALID_CHAT_ROOM_MEMBER_TYPE"
    INVALID_CHAT_ROOM_ACCESS_CRITERIA = "INVALID_CHAT_ROOM_ACCESS_CRITERIA"
    CANNOT_ADD_CRITERIA_T0_CHAT_ROOM = "CANNOT_ADD_CRITERIA_T0_CHAT_ROOM"
    CHAT_ROOM_SUBSCRIPTION_ALREADY_EXISTS = "CHAT_ROOM_SUBSCRIPTION_ALREADY_EXISTS"

    EMAIL_REQUIRED = "EMAIL_REQUIRED"
    USERNAME_REQUIRED = "USERNAME_REQUIRED"
    USER_REQUIRED= "USER_REQUIRED"
    EVENT_REQUIRED = "EVENT_REQUIRED"
    INTERLOCUTOR_REQUIRED = "INTERLOCUTOR_REQUIRED"
    PRIVATE_CHAT_ROOM_NOT_FOUND_BETWEEN_USERS = "PRIVATE_CHAT_ROOM_NOT_FOUND_BETWEEN_USERS"


class TransactionKindEnum(BaseEnum):
    WITHDRAW = "WITHDRAW"
    SUBSCRIPTION = "SUBSCRIPTION"
    EVENT_HIGHLIGHTING = "EVENT_HIGHLIGHTING"
    ORDER = "ORDER"


class TransactionStatusEnum(BaseEnum):
    PENDING = "PENDING"  # transaction start
    IN_PROGRESS = "IN_PROGRESS"  # transaction is in progress
    PAID = "PAID"  # transaction has paid
    CANCELED = "CANCELED"  # transaction has cancelled
    FAILED = "FAILED"  # transaction has failed
    RESOLVED = (
        "RESOLVED"  # transaction has resolved without paid but can be taking as paid
    )


class WithdrawStatusEnum(BaseEnum):
    CREATED = "CREATED"  # withdraw is created
    FAILED = "FAILED"  # withdraw has failed
    FINISHED = "FINISHED"  # withdraw is finished
    PROCESSING = "PROCESSING"  # withdraw is being processing
    INITIALIZED = "INITIALIZED"  # withdraw is initialized


class OrderStatusEnum(BaseEnum):
    SUBMITTED = "SUBMITTED"  # withdraw is created
    STARTED = "STARTED"  # withdraw has failed
    FINISHED = "FINISHED"  # withdraw is finished


class WithdrawMethodEnum(BaseEnum):
    MTN_BENIN = "MTN_BENIN"
    MOOV_BENIN = "MOOV_BENIN"


class TRANSACTIONS_POSSIBLE_GATEWAYS(BaseEnum):
    FEDAPAY = "FEDAPAY"
    PAYSTACK = "PAYSTACK"
    STRIPE = "STRIPE"
    MANUAL = "MANUAL"
    INTERNAL_AUTO = "INTERNAL_AUTO"
    FREE_SHIPPING = "FREE_SHIPPING"


class PAYMENT_METHOD(BaseEnum):
    CASH = "CASH"
    MOMO = "MOMO"
    CARD = "CARD"


class FEDAPAY_ENDPOINT_ENUM(BaseEnum):
    # BASE_URL = "https://sandbox-api.fedapay.com"
    # PRIVATE_KEY = "sk_sandbox_ypeP3At4eGmMsLjUAvRQItoU"

    PRIVATE_KEY = "	sk_live_QLFYJNJZkLDMMSK3xFM0_hlu"
    BASE_URL = "https://api.fedapay.com"

    CREATE_TRANSACTION = "/v1/transactions"
    STATUS_TRANSACTION = "/v1/transactions/{id}"
    GET_TRANSACTION_LINK = "/v1/transactions/{id}/token"

    CREATION_PAYOUT = "/v1/payouts"
    START_PAYOUT = "/v1/payouts/start"
    STATUS_PAYOUT = "/v1/payouts/:id"


class NOTIFICATION_TYPES_ENUM(BaseEnum):
    WELCOME = "WELCOME"
    ORDER_RECEIPT = "ORDER_RECEIPT"
    EVENT_VALIDATED = "EVENT_VALIDATED"
    NEW_EVENT_CREATION = "NEW_EVENT_CREATION"
    ACCOUNT_VALIDATION_REQUEST = "ACCOUNT_VALIDATION_REQUEST"
    ACCOUNT_VALIDATION_SUCCESSFUL = "ACCOUNT_VALIDATION_SUCCESSFUL"
    WITHDRAW_REQUEST_SUCCESSFUL = "WITHDRAW_REQUEST_SUCCESSFUL"
    PASSWORD_RESET_REQUEST = "PASSWORD_RESET_REQUEST"
    FOLLOWED_EVENT_PUBLISHER = "FOLLOWED_EVENT_PUBLISHER"
    FAVOURITE_CATEGORY_EVENT = "FAVOURITE_CATEGORY_EVENT"
    PASSWORD_RESET_SUCCESSFUL = "PASSWORD_RESET_SUCCESSFUL"
    APPROACH_OF_FAVOURED_EVENT = "APPROACH_OF_FAVOURED_EVENT"
    NEARLY_SOLD_OUT_OF_TICKETS = "NEARLY_SOLD_OUT_OF_TICKETS"
    END_OF_TRANSACTION_PROCESSING = "END_OF_TRANSACTION_PROCESSING"
    EVENT_LOCATION_NEAR_BY_USER_POI = "EVENT_LOCATION_NEAR_BY_USER_POI"
    EVENT_NEAR_BY_USER_LAST_LOCATION = "EVENT_NEAR_BY_USER_LAST_LOCATION"
    END_OF_TICKETS_GENERATION_FOR_ORDER = "END_OF_TICKETS_GENERATION_FOR_ORDER"
    END_OF_TICKETS_GENERATION_FOR_ANONYMOUS_ORDER = "END_OF_TICKETS_GENERATION_FOR_ANONYMOUS_ORDER"
    EVENT_LOCATION_INSIDE_ZONE_OF_INTEREST = "EVENT_LOCATION_INSIDE_ZONE_OF_INTEREST"
    NEW_EVENT_CREATION_IN_FAVORED_CATEGORY = "NEW_EVENT_CREATION_IN_FAVORED_CATEGORY"
    NEW_MEMBERSHIP_CREATION = "NEW_MEMBERSHIP_CREATION"
    NEARLY_SOLD_OUT_OF_TICKETS_OF_FAVOURED_EVENT = (
        "NEARLY_SOLD_OUT_OF_TICKETS_OF_FAVOURED_EVENT"
    )
    EVENT_HIGHLIGHTING_SUCCESSFUL = "EVENT_HIGHLIGHTING_SUCCESSFUL"
    SUBSCRIPTION_SUCCESSFUL = "SUBSCRIPTION_SUCCESSFUL"


class NOTIFICATION_TYPE_TEMPLATE_BY_CHANNEL_ENUM(BaseEnum):
    ORDER_RECEIPT = "4H4RRMFYW44Z2ZHVNEG5T7NSC4TT"
    NEW_EVENT_CREATION_IN_FAVORED_CATEGORY = "9EDRXFVKYF4947GX0NXD72NPG6ZS"
    NEW_EVENT_CREATION = "HS0YC15YTV4J3XHVSPSAE50QZ1T8"
    END_OF_TICKETS_GENERATION_FOR_ORDER = "W47TZVTQ05MFN7K2VTWAX7Q8FXVH"
    APPROACH_OF_FAVOURED_EVENT = "Y1VRF3D1AR46C5GQ0XMDJWHYY9GA"
    NEARLY_SOLD_OUT_OF_TICKETS_OF_FAVOURED_EVENT = "NPQKZN7CXFMJJYQZTYXG12SE7HXA"
    NEARLY_SOLD_OUT_OF_TICKETS = "1ZSCSGKFTAMG55QNHC3P6XGAGEA7"
    WELCOME = "05FD1AHS6T4WBKGNZ0JA282WY0E0"
    ACCOUNT_VALIDATION_REQUEST = "R6CH606A74420MG2B1B6166BPS0S"
    ACCOUNT_VALIDATION_SUCCESSFUL = "9S16KT0XP54AVHNYKMTK0PBCY3QA"
    PASSWORD_RESET_REQUEST = "BSTBXAJQM4M74TNFVGK1F1AF4FNS"
    PASSWORD_RESET_SUCCESSFUL = "4NRAXFHWK54RX2JQH3P2Y4DHRQ9J"
    EVENT_VALIDATED = "BH06YK5V9Y4KY6GVGTJJG90PK5KP"
    # Todo:
    WITHDRAW_REQUEST = "2QF53K5N35MVR4QGMAZDBR0N3GR6"
    WITHDRAW_REQUEST_SUCCESSFUL = "2QF53K5N35MVR4QGMAZDBR0N3GR6"
    EVENT_HIGHLIGHTING_SUCCESSFUL = "WTZ6R1ABEMMQ7PQNR6VYNZYVSTAB"
    SUBSCRIPTION_SUCCESSFUL = "G25XD32TBWM9HTNPAKQHZACG1PSJ"
    END_OF_TRANSACTION_PROCESSING = "DKXQAET3SP4MX7Q7VV2XYP816BZB"
    NEW_MEMBERSHIP_CREATION = "ZW854BBMDB4ZE4JZBG5XG5A3DNF6"
    EVENT_NEAR_BY_USER_LAST_LOCATION = "694MHXW4KP4JT4HVE1S573R7GFB4"


class NOTIFICATION_STATUS_ENUM(BaseEnum):
    FAILED = "FAILED"
    SUCCESS = "SUCCESS"


class NOTIFICATION_CHANNELS_ENUM(BaseEnum):
    WHATSAPP = "WHATSAPP"
    EMAIL = "EMAIL"
    INBOX = "INBOX"
    PUSH = "PUSH"
    SMS = "SMS"


class VARIABLE_NAMES_ENUM(BaseEnum):
    TICKET_NEARLY_SOLD_OUT_PERCENTAGES_FOR_NOTIFICATIONS = (
        "TICKET_NEARLY_SOLD_OUT_PERCENTAGES_FOR_NOTIFICATIONS"
    )
    EVENT_APPROACH_NOTIFICATIONS_MOMENTS = "EVENT_APPROACH_NOTIFICATIONS_MOMENTS"
    PERCENTAGE_ABOUT_A_TICKET_SELLING = "PERCENTAGE_ABOUT_A_TICKET_SELLING"
    PERCENTAGE_ABOUT_A_TICKET_SELLING_WITH_DISCOUNT = (
        "PERCENTAGE_ABOUT_A_TICKET_SELLING_WITH_DISCOUNT"
    )
    CURRENT_SITE_BASE_ADDRESS = "CURRENT_SITE_BASE_ADDRESS"
    MINIMAL_AMOUNT_REQUIRED_FOR_WITHDRAW = "MINIMAL_AMOUNT_REQUIRED_FOR_WITHDRAW"
    MINIMAL_AMOUNT_REQUIRED_TO_COVER_WITHDRAWALS_COST = (
        "MINIMAL_AMOUNT_REQUIRED_TO_COVER_WITHDRAWALS_COST"
    )


class DISCOUNT_TARGET_TYPES_ENUM(BaseEnum):
    EVENT_HIGHLIGHTING = "EVENT_HIGHLIGHTING"
    SUBSCRIPTION = "SUBSCRIPTION"
    TICKET = "TICKET"


class DISCOUNT_TYPES_ENUM(BaseEnum):
    FREE_SHIPPING = "FREE_SHIPPING"
    PERCENTAGE = "PERCENTAGE"
    FIXED = "FIXED"


class DISCOUNT_USE_ENTITY_TYPES_ENUM(BaseEnum):
    ORGANIZATION = "ORGANIZATION"
    USER = "USER"


class DISCOUNT_CONDITION_ENTITY_TYPES_ENUM(BaseEnum):
    EVENT_HIGHLIGHTING_TYPES = "EVENT_HIGHLIGHTING_TYPES"
    SUBSCRIPTION_TYPES = "SUBSCRIPTION_TYPES"
    ORGANIZATIONS = "ORGANIZATIONS"
    USERS = "USERS"

    # Related to ticket buying
    EVENTS = "EVENTS"
    TICKETS = "TICKETS"
    TICKET_CATEGORIES = "TICKET_CATEGORIES"


class DISCOUNT_CONDITION_OPERATORS_ENUM(BaseEnum):
    IN = "IN"
    NOT_IN = "NOT_IN"


class ChatRoomTypeEnum(BaseEnum):
    PRIMARY = "PRIMARY"
    SECONDARY = "SECONDARY"
    PERSONAL = "PERSONAL"


class ChatRoomVisibilityEnum(BaseEnum):
    PUBLIC = "PUBLIC"
    PRIVATE = "PRIVATE"


class ChatRoomStatusEnum(BaseEnum):
    ACTIVE = "ACTIVE"
    CLOSED = "CLOSED"


class NotificationLevelEnum(BaseEnum):
    ALL = "ALL"
    MENTIONS = "MENTIONS"
    NONE = "NONE"


class AccessCriteriaTypeEnum(BaseEnum):
    ROLE = "ROLE"
    EVENT_TICKET = "EVENT_TICKET"


class ChatRoomRolesEnum(BaseEnum):
    ADMIN = "ADMIN"
    USER = "USER"


class OrganizationRolesEnum(BaseEnum):
    MEMBER = "Member"
    COORDINATOR = "Coordinator"
