# Generated by Django 5.1.7 on 2025-03-10 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_rooms', '0002_chatroom_tags_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chatroom',
            name='chatroom_tags_gin_idx',
        ),
    ]
