# Generated by Django 5.1.7 on 2025-03-23 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_rooms', '0003_remove_chatroom_chatroom_tags_gin_idx'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('event', 'title')},
        ),
    ]
