# Generated by Django 5.2.4 on 2025-07-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_rooms', '0004_alter_chatroom_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatroomsubscription',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='type',
            field=models.CharField(choices=[('PRIMARY', 'PRIMARY'), ('SECONDARY', 'SECONDARY'), ('PERSONAL', 'PERSONAL')], default='SECONDARY', help_text='Type du salon (principal ou secondaire)', max_length=20, verbose_name='Type'),
        ),
    ]
