# Generated by Django 5.1.6 on 2025-02-25 14:00

import commons.utils
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0010_alter_eventhighlighting_end_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="New",
            fields=[
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d' ajout"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True, verbose_name="Désigne si l' instance est active"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Titre")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "cover_image",
                    models.ImageField(
                        upload_to=commons.utils._upload_to,
                        verbose_name="Image de couverture",
                    ),
                ),
                (
                    "dynamic_link",
                    models.CharField(max_length=512, verbose_name="Lien dynamique"),
                ),
                ("expired_at", models.DateField(verbose_name="Date d'expiration")),
                ("status", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="news",
                        to="events.event",
                        verbose_name="Evenement relatif",
                    ),
                ),
            ],
            options={
                "verbose_name": "Actualité",
                "verbose_name_plural": "Actualités",
            },
        ),
    ]
