# Generated by Django 5.1.6 on 2025-02-25 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0011_alter_ticket_expiry_date"),
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="new",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="news",
                to="events.event",
                verbose_name="Evenement relatif",
            ),
        ),
    ]
