# Generated by Django 5.1.7 on 2025-03-09 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_eventhighlighting_end_date_and_more'),
        ('news', '0002_alter_new_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='events.event', verbose_name='Evenement relatif'),
        ),
    ]
