# Generated by Django 5.1.1 on 2024-09-12 18:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name="Date d' ajout")),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('active', models.BooleanField(default=True, verbose_name="Désigne si l' instance est active")),
                ('name', models.CharField(blank=True, max_length=220, verbose_name='')),
                ('code', models.CharField(blank=True, max_length=2, verbose_name='')),
                ('prefix', models.CharField(blank=True, max_length=5, verbose_name='')),
                ('is_covered', models.BooleanField(default=False, verbose_name='')),
            ],
            options={
                'verbose_name': 'Pays',
                'verbose_name_plural': 'Pays',
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name="Date d' ajout")),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('active', models.BooleanField(default=True, verbose_name="Désigne si l' instance est active")),
                ('label', models.CharField(default='The Label', max_length=520)),
                ('name', models.CharField(choices=[('TICKET_NEARLY_SOLD_OUT_PERCENTAGES_FOR_NOTIFICATIONS', 'TICKET_NEARLY_SOLD_OUT_PERCENTAGES_FOR_NOTIFICATIONS'), ('EVENT_APPROACH_NOTIFICATIONS_MOMENTS', 'EVENT_APPROACH_NOTIFICATIONS_MOMENTS'), ('PERCENTAGE_ABOUT_A_TICKET_SELLING', 'PERCENTAGE_ABOUT_A_TICKET_SELLING'), ('CURRENT_SITE_BASE_ADDRESS', 'CURRENT_SITE_BASE_ADDRESS'), ('MINIMAL_AMOUNT_REQUIRED_FOR_WITHDRAW', 'MINIMAL_AMOUNT_REQUIRED_FOR_WITHDRAW'), ('MINIMAL_AMOUNT_REQUIRED_TO_COVER_WITHDRAWALS_COST', 'MINIMAL_AMOUNT_REQUIRED_TO_COVER_WITHDRAWALS_COST')], max_length=120, unique=True)),
                ('type', models.CharField(choices=[('float', 'Float'), ('int', 'Int'), ('str', 'String')], max_length=120)),
                ('is_unique', models.BooleanField(default=False, verbose_name='Désigne si la variable à une valeur unique')),
                ('editable', models.BooleanField(default=True, verbose_name='Désigne si la variable peut être modifiée')),
            ],
            options={
                'verbose_name': 'Variable',
                'verbose_name_plural': 'Variables',
            },
        ),
        migrations.CreateModel(
            name='CeleryTask',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name="Date d' ajout")),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('active', models.BooleanField(default=True, verbose_name="Désigne si l' instance est active")),
                ('type', models.CharField(blank=True, choices=[('DATABASE_BACKUP', 'DATABASE_BACKUP'), ('PAYMENT_TRANSACTION_CALLBACK', 'PAYMENT_TRANSACTION_CALLBACK')], max_length=220, verbose_name='Type de la tache')),
                ('status', models.CharField(blank=True, choices=[('TASK_STATUS_INITIALIZED', 'TASK_STATUS_INITIALIZED'), ('TASK_STATUS_PENDING', 'TASK_STATUS_PENDING'), ('TASK_STATUS_FINISHED', 'TASK_STATUS_FINISHED')], max_length=220, verbose_name='Status de la tache')),
                ('task_id', models.CharField(blank=True, max_length=220, verbose_name='Id de la tâche')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de début')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('object_id', models.CharField(max_length=225)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VariableValue',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name="Date d' ajout")),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('active', models.BooleanField(default=True, verbose_name="Désigne si l' instance est active")),
                ('value', models.CharField(max_length=220, verbose_name='Valeur de la variable')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='possible_values', to='utils.variable', verbose_name='Variable relative')),
            ],
            options={
                'verbose_name': "Valeur d' une Variable",
                'verbose_name_plural': 'Valeurs des Variables',
            },
        ),
    ]
