# Generated by Django 5.1.1 on 2024-10-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='unit',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
