# Generated by Django 5.2.1 on 2025-10-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_alter_variable_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(blank=True, max_length=2, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='country',
            name='is_covered',
            field=models.BooleanField(default=False, verbose_name='Désigne si les services couvrent ce pays.'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(blank=True, max_length=220, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='country',
            name='prefix',
            field=models.CharField(blank=True, max_length=5, verbose_name='Préfixe'),
        ),
    ]
