# Generated by Django 5.1.4 on 2024-12-29 15:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_eventhighlighting_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eticket',
            old_name='related_order_id',
            new_name='old_related_order_id',
        ),
        migrations.AddField(
            model_name='eticket',
            name='related_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='related_e_tickets', to='events.order', verbose_name='Commende relative'),
        ),
        migrations.AlterField(
            model_name='eventhighlighting',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 1, 5), verbose_name='Date de fin de validité'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 29, 22, 22, 57, 393726), verbose_name='Date de fin de validité'),
        ),
    ]
