# Generated by Django 5.1.1 on 2024-10-21 10:59

import apps.users.models.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apppermission',
            options={'ordering': ('entity',), 'verbose_name': "Permission de l' application", 'verbose_name_plural': "Permissions de l' application"},
        ),
        migrations.AddField(
            model_name='historicaltransaction',
            name='coupon_metadata',
            field=models.JSONField(default=apps.users.models.utils.get_transaction_default_coupon_metadata, verbose_name='Données de réduction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='coupon_metadata',
            field=models.JSONField(default=apps.users.models.utils.get_transaction_default_coupon_metadata, verbose_name='Données de réduction'),
        ),
        migrations.AlterField(
            model_name='historicaltransaction',
            name='gateway',
            field=models.CharField(choices=[('FEDAPAY', 'FEDAPAY'), ('PAYSTACK', 'PAYSTACK'), ('STRIPE', 'STRIPE'), ('MANUAL', 'MANUAL'), ('INTERNAL_AUTO', 'INTERNAL_AUTO')], default='FEDAPAY', max_length=255, null=True, verbose_name='Passerelle de paiement utilisé'),
        ),
        migrations.AlterField(
            model_name='historicaltransaction',
            name='last_webhook_data',
            field=models.JSONField(default=apps.users.models.utils.get_transaction_default_last_webhook_data, verbose_name='Dernière données de mise à jour'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='gateway',
            field=models.CharField(choices=[('FEDAPAY', 'FEDAPAY'), ('PAYSTACK', 'PAYSTACK'), ('STRIPE', 'STRIPE'), ('MANUAL', 'MANUAL'), ('INTERNAL_AUTO', 'INTERNAL_AUTO')], default='FEDAPAY', max_length=255, null=True, verbose_name='Passerelle de paiement utilisé'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='last_webhook_data',
            field=models.JSONField(default=apps.users.models.utils.get_transaction_default_last_webhook_data, verbose_name='Dernière données de mise à jour'),
        ),
    ]
