# Generated by Django 5.1.7 on 2025-03-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_apppermission_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltransaction',
            name='gateway',
            field=models.CharField(choices=[('FEDAPAY', 'FEDAPAY'), ('PAYSTACK', 'PAYSTACK'), ('STRIPE', 'STRIPE'), ('MANUAL', 'MANUAL'), ('INTERNAL_AUTO', 'INTERNAL_AUTO'), ('FREE_SHIPPING', 'FREE_SHIPPING')], default='FEDAPAY', max_length=255, null=True, verbose_name='Passerelle de paiement utilisé'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='gateway',
            field=models.CharField(choices=[('FEDAPAY', 'FEDAPAY'), ('PAYSTACK', 'PAYSTACK'), ('STRIPE', 'STRIPE'), ('MANUAL', 'MANUAL'), ('INTERNAL_AUTO', 'INTERNAL_AUTO'), ('FREE_SHIPPING', 'FREE_SHIPPING')], default='FEDAPAY', max_length=255, null=True, verbose_name='Passerelle de paiement utilisé'),
        ),
    ]
