# Generated by Django 5.2.3 on 2025-06-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='register_from',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name="Désigne la source d'inscription"),
        ),
    ]
