# Generated by Django 5.1.1 on 2024-09-12 18:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsArea',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name="Date d' ajout")),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('active', models.BooleanField(default=True, verbose_name="Désigne si l' instance est active")),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=150, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=150, verbose_name='Numero de téléphone')),
                ('subject', models.CharField(max_length=150, verbose_name='Sujet')),
                ('message', models.TextField(max_length=150, verbose_name='Message')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Message Contact',
                'verbose_name_plural': 'Messages de Contact',
            },
        ),
        migrations.CreateModel(
            name='RegistrationsForNewsletter',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name="Date d' ajout")),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('active', models.BooleanField(default=True, verbose_name="Désigne si l' instance est active")),
                ('email', models.EmailField(blank=True, max_length=150, verbose_name='Adresse email')),
                ('conf_num', models.CharField(max_length=15, verbose_name='Numero de confirmation')),
                ('confirmed', models.BooleanField(default=False, verbose_name="Désigne si l'inscription est confirmé")),
            ],
            options={
                'verbose_name': 'Souscription pour les newsletters',
                'verbose_name_plural': 'Souscriptions pour les newsletters',
            },
        ),
    ]
