# Generated by Django 5.1.1 on 2024-10-21 10:59

import apps.marketing.helpers.discounts.helpers
import apps.utils.utils.codes.utils
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
        ('organizations', '0003_historicalorganization_percentage_if_discounted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountUsageRule',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name="Date d' ajout")),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('active', models.BooleanField(default=True, verbose_name="Désigne si l' instance est active")),
                ('entity_type', models.CharField(choices=[('ORGANIZATION', 'ORGANIZATION'), ('USER', 'USER')], default='USER', max_length=220, verbose_name="Type de l' entité")),
                ('max_uses', models.BigIntegerField(blank=True, default=None, null=True, verbose_name="Maximum d' usage")),
            ],
            options={
                'verbose_name': "Limite d' usage de réduction",
                'verbose_name_plural': "Limites d' usage des réductions",
            },
        ),
        migrations.CreateModel(
            name='DiscountValidationRule',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name="Date d' ajout")),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('active', models.BooleanField(default=True, verbose_name="Désigne si l' instance est active")),
                ('type', models.CharField(choices=[('FREE_SHIPPING', 'FREE_SHIPPING'), ('PERCENTAGE', 'PERCENTAGE'), ('FIXED', 'FIXED')], default='PERCENTAGE', max_length=128, verbose_name='Type')),
                ('value', models.IntegerField(blank=True, default=None, null=True, verbose_name='Valeur')),
            ],
            options={
                'verbose_name': 'Règle de réduction',
                'verbose_name_plural': 'Règles de réductions',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name="Date d' ajout")),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('active', models.BooleanField(default=True, verbose_name="Désigne si l' instance est active")),
                ('label', models.CharField(max_length=256, unique=True, verbose_name='Label de la reduction')),
                ('target_type', models.CharField(choices=[('EVENT_HIGHLIGHTING', 'EVENT_HIGHLIGHTING'), ('SUBSCRIPTION', 'SUBSCRIPTION'), ('TICKET', 'TICKET')], default='TICKET', max_length=220, verbose_name='Type de réduction')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de début')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('is_dynamic', models.BooleanField(default=True, verbose_name='Désigne si la reduction est dynamique')),
                ('minimal_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Montant minimal requis')),
                ('usage_limit', models.BigIntegerField(blank=True, default=None, null=True, verbose_name="Limite d' usage")),
                ('usages_count', models.BigIntegerField(blank=True, default=0, null=True, verbose_name="Nombre d' usage")),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='organizations.organization', verbose_name='Organisation relative')),
                ('usage_rule', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount', to='marketing.discountusagerule', verbose_name="Règle sur la limite d' usage")),
                ('validation_rule', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount', to='marketing.discountvalidationrule', verbose_name='Règle de validation')),
            ],
            options={
                'verbose_name': 'Reduction',
                'verbose_name_plural': 'Reductions',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name="Date d' ajout")),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('active', models.BooleanField(default=True, verbose_name="Désigne si l' instance est active")),
                ('code', models.CharField(db_index=True, default=apps.marketing.helpers.discounts.helpers.get_random_code, max_length=12, unique=True, verbose_name='Coupon Code')),
                ('usages', models.IntegerField(default=0, editable=False, verbose_name='Usage Count')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.discount')),
            ],
            options={
                'verbose_name': 'Coupon de Réduction',
                'verbose_name_plural': 'Coupons de Réduction',
            },
        ),
        migrations.CreateModel(
            name='DiscountUsage',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name="Date d' ajout")),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('active', models.BooleanField(default=True, verbose_name="Désigne si l' instance est active")),
                ('entity_id', models.CharField(max_length=128, verbose_name="Id de l' entité")),
                ('entity_type', models.CharField(choices=[('ORGANIZATION', 'ORGANIZATION'), ('USER', 'USER')], max_length=220, verbose_name="Type de l' entité")),
                ('usages', models.IntegerField(default=0, editable=False, verbose_name='Utilisation')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='marketing.discount', verbose_name='Réductions')),
            ],
            options={
                'verbose_name': 'Utilisation de réduction',
                'verbose_name_plural': 'Utilisations de réduction',
            },
        ),
        migrations.CreateModel(
            name='DiscountCondition',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name="Date d' ajout")),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('active', models.BooleanField(default=True, verbose_name="Désigne si l' instance est active")),
                ('entity_type', models.CharField(choices=[('EVENT_HIGHLIGHTING_TYPES', 'EVENT_HIGHLIGHTING_TYPES'), ('SUBSCRIPTION_TYPES', 'SUBSCRIPTION_TYPES'), ('ORGANIZATIONS', 'ORGANIZATIONS'), ('USERS', 'USERS'), ('EVENTS', 'EVENTS'), ('TICKETS', 'TICKETS'), ('TICKET_CATEGORIES', 'TICKET_CATEGORIES')], default='ORGANIZATIONS', max_length=128, verbose_name='Entité relative')),
                ('operator', models.CharField(choices=[('IN', 'IN'), ('NOT_IN', 'NOT_IN')], default='IN', max_length=128, verbose_name='Opérateur')),
                ('target_ids', models.JSONField(default=apps.utils.utils.codes.utils.get_blank_dict, verbose_name="Ids de l' entité cible")),
                ('validation_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='marketing.discountvalidationrule', verbose_name='Règle relative')),
            ],
            options={
                'verbose_name': 'Condition de réduction',
                'verbose_name_plural': 'Condition de réductions',
            },
        ),
    ]
