# Generated by Django 5.1.1 on 2024-10-23 04:19

import apps.marketing.helpers.discounts.helpers
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_discountusagerule_discountvalidationrule_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(db_index=True, default=apps.marketing.helpers.discounts.helpers.get_random_code, max_length=12, unique=True, verbose_name='Code coupon'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='marketing.discount', verbose_name='Réduction associée'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='usages',
            field=models.IntegerField(default=0, editable=False, verbose_name='Nombre de fois utilisé'),
        ),
    ]
