# Generated by Django 5.1.7 on 2025-04-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_alter_coupon_code_alter_coupon_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_auto_generated',
            field=models.BooleanField(default=False, help_text='Indique si ce coupon a été généré automatiquement par le système', verbose_name='Généré automatiquement'),
        ),
        migrations.AddField(
            model_name='discount',
            name='is_automatic',
            field=models.BooleanField(default=False, help_text='Si activé, la réduction sera appliquée automatiquement aux commandes éligibles', verbose_name='Appliquer automatiquement'),
        ),
    ]
