# Generated by Django 5.2.1 on 2025-11-02 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0021_alter_eventhighlighting_end_date_and_more'),
        ('organizations', '0005_historicalorganization_organization_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp')], default='EMAIL', max_length=10)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('ACCEPTED', 'Acceptée'), ('DECLINED', 'Refusée'), ('EXPIRED', 'Expirée'), ('CANCELED', 'Annulée')], db_index=True, default='PENDING', max_length=12)),
                ('message', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_seller_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_invites_received', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_invitations', to='events.seller')),
                ('super_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_invitations', to='organizations.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['super_seller', 'status'], name='super_selle_super_s_5862f4_idx'), models.Index(fields=['email', 'phone'], name='super_selle_email_bbb4f2_idx'), models.Index(fields=['expires_at'], name='super_selle_expires_204747_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('email__gt', ''), ('phone__gt', ''), _connector='OR'), name='seller_invitation_contact_required')],
            },
        ),
    ]
