# Generated by Django 5.2.1 on 2025-11-07 16:04

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_alter_ticket_expiry_date'),
        ('super_sellers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerWallet',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name="Date d' ajout")),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('active', models.BooleanField(default=True, verbose_name="Désigne si l' instance est active")),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Solde actuel disponible pour retrait', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Solde disponible')),
                ('pending_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Solde en attente de traitement (retraits en cours)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Solde en attente')),
                ('total_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total cumulé de tous les gains (historique)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total gagné')),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total cumulé de tous les retraits effectués', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total retiré')),
                ('last_transaction_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernière transaction')),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='events.seller', verbose_name='Vendeur')),
            ],
            options={
                'verbose_name': 'Portefeuille vendeur',
                'verbose_name_plural': 'Portefeuilles vendeurs',
            },
        ),
        migrations.CreateModel(
            name='SellerWithdrawal',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name="Date d' ajout")),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('active', models.BooleanField(default=True, verbose_name="Désigne si l' instance est active")),
                ('amount', models.DecimalField(decimal_places=2, help_text='Montant minimum: 1000 F CFA', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1000.00'))], verbose_name='Montant demandé')),
                ('fees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Frais facturés pour ce retrait', max_digits=12, verbose_name='Frais de traitement')),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Montant après déduction des frais', max_digits=12, verbose_name='Montant net à recevoir')),
                ('method', models.CharField(choices=[('MOBILE_MONEY_MTN', 'Mobile Money MTN'), ('MOBILE_MONEY_MOOV', 'Mobile Money MOOV'), ('BANK_TRANSFER', 'Virement bancaire')], max_length=30, verbose_name='Méthode de retrait')),
                ('payment_phone', models.CharField(blank=True, help_text='Pour Mobile Money uniquement', max_length=20, null=True, verbose_name='Numéro de téléphone')),
                ('bank_account_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom du compte bancaire')),
                ('bank_account_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de compte bancaire')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom de la banque')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('PROCESSING', 'En cours de traitement'), ('COMPLETED', 'Terminé'), ('FAILED', 'Échoué'), ('CANCELLED', 'Annulé'), ('REJECTED', 'Rejeté')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Demandé le')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approuvé le')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Traité le')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Complété le')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Raison du rejet')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de tentatives')),
                ('max_retry_count', models.PositiveIntegerField(default=3, verbose_name='Nombre maximum de tentatives')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name="Message d'erreur")),
                ('processing_logs', models.JSONField(default=list, help_text='Historique détaillé de toutes les tentatives', verbose_name='Logs de traitement')),
                ('provider_reference', models.CharField(blank=True, help_text='Référence de transaction du provider (FedaPay, etc.)', max_length=255, null=True, verbose_name='Référence fournisseur')),
                ('provider_response', models.JSONField(blank=True, help_text="Réponse complète de l'API de paiement", null=True, verbose_name='Réponse du fournisseur')),
                ('notes', models.TextField(blank=True, help_text='Notes internes administratives', null=True, verbose_name='Notes')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_withdrawals', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='events.seller', verbose_name='Vendeur')),
            ],
            options={
                'verbose_name': 'Demande de retrait vendeur',
                'verbose_name_plural': 'Demandes de retrait vendeurs',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name="Date d' ajout")),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('active', models.BooleanField(default=True, verbose_name="Désigne si l' instance est active")),
                ('transaction_type', models.CharField(choices=[('SALE', 'Vente de ticket'), ('COMMISSION', 'Commission'), ('WITHDRAWAL', 'Retrait'), ('REFUND', 'Remboursement'), ('ADJUSTMENT', 'Ajustement manuel'), ('BONUS', 'Bonus')], max_length=20, verbose_name='Type de transaction')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positif pour crédit, négatif pour débit', max_digits=12, verbose_name='Montant')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Solde après transaction')),
                ('reference', models.CharField(blank=True, help_text='Référence externe (order_id, withdrawal_id, etc.)', max_length=255, verbose_name='Référence')),
                ('metadata', models.JSONField(default=dict, help_text='Données supplémentaires (event_id, ticket_id, etc.)', verbose_name='Métadonnées')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='super_sellers.sellerwallet', verbose_name='Portefeuille')),
            ],
            options={
                'verbose_name': 'Transaction wallet',
                'verbose_name_plural': 'Transactions wallet',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='sellerwallet',
            index=models.Index(fields=['seller', '-timestamp'], name='super_selle_seller__499ef2_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerwallet',
            index=models.Index(fields=['balance'], name='super_selle_balance_e9eadc_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerwithdrawal',
            index=models.Index(fields=['seller', '-requested_at'], name='super_selle_seller__05bbed_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerwithdrawal',
            index=models.Index(fields=['status', '-requested_at'], name='super_selle_status_43f9de_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerwithdrawal',
            index=models.Index(fields=['method', 'status'], name='super_selle_method_bf7d69_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerwithdrawal',
            index=models.Index(fields=['provider_reference'], name='super_selle_provide_86c97c_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['wallet', '-timestamp'], name='super_selle_wallet__ad786b_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['transaction_type', '-timestamp'], name='super_selle_transac_3ba9af_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['reference'], name='super_selle_referen_5f3b7b_idx'),
        ),
    ]
