# Generated by Django 5.2.1 on 2025-11-09 18:31

import apps.super_sellers.models.kyc_submission
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_alter_eventhighlighting_end_date_and_more'),
        ('organizations', '0005_historicalorganization_organization_type_and_more'),
        ('super_sellers', '0002_sellerwallet_sellerwithdrawal_wallettransaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.CharField(blank=True, max_length=512)),
                ('file_format', models.CharField(choices=[('PDF', 'PDF'), ('CSV', 'CSV')], default='PDF', max_length=6)),
                ('sent_via_email', models.BooleanField(default=False)),
                ('sent_via_whatsapp', models.BooleanField(default=False)),
                ('send_log', models.JSONField(blank=True, default=dict)),
                ('super_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_reports', to='organizations.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['super_seller', 'generated_at'], name='super_selle_super_s_7f0e84_idx'), models.Index(fields=['period_start', 'period_end'], name='super_selle_period__4f937a_idx')],
            },
        ),
        migrations.CreateModel(
            name='SalesReportPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('DAILY', 'Quotidien'), ('WEEKLY', 'Hebdomadaire'), ('MONTHLY', 'Mensuel')], default='WEEKLY', max_length=10)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('BOTH', 'Email + WhatsApp')], default='EMAIL', max_length=10)),
                ('fmt', models.CharField(choices=[('PDF', 'PDF'), ('CSV', 'CSV')], default='PDF', max_length=6)),
                ('time_of_day', models.TimeField(default='08:00')),
                ('weekday', models.IntegerField(default=1)),
                ('day_of_month', models.IntegerField(default=1)),
                ('email_recipients', models.JSONField(blank=True, default=list)),
                ('whatsapp_recipients', models.JSONField(blank=True, default=list)),
                ('include_by_seller', models.BooleanField(default=True)),
                ('include_by_event', models.BooleanField(default=True)),
                ('include_period_detail', models.BooleanField(default=True)),
                ('include_graphs', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('super_seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_pref', to='organizations.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['super_seller'], name='super_selle_super_s_629b20_idx'), models.Index(fields=['active', 'frequency'], name='super_selle_active_49e6bd_idx')],
            },
        ),
        migrations.CreateModel(
            name='SellerKYCSubmission',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name="Date d' ajout")),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('active', models.BooleanField(default=True, verbose_name="Désigne si l' instance est active")),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('VERIFIED', 'Vérifié'), ('REJECTED', 'Rejeté'), ('NOT_REQUIRED', 'Non requis')], db_index=True, default='PENDING', max_length=20)),
                ('identity_type', models.CharField(choices=[('PASSPORT', 'Passeport'), ('ID_CARD', 'Carte d’identité'), ('DRIVER_LICENSE', 'Permis de conduire')], max_length=20)),
                ('passport_image', models.FileField(blank=True, null=True, upload_to=apps.super_sellers.models.kyc_submission.kyc_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])])),
                ('id_front', models.FileField(blank=True, null=True, upload_to=apps.super_sellers.models.kyc_submission.kyc_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])])),
                ('id_back', models.FileField(blank=True, null=True, upload_to=apps.super_sellers.models.kyc_submission.kyc_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])])),
                ('selfie_with_document', models.FileField(blank=True, null=True, upload_to=apps.super_sellers.models.kyc_submission.kyc_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('proof_of_address', models.FileField(blank=True, null=True, upload_to=apps.super_sellers.models.kyc_submission.kyc_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])])),
                ('additional_documents', models.JSONField(blank=True, default=list)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_kyc_reviewed', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_submissions', to='events.seller')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_kyc_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['seller', 'status'], name='super_selle_seller__0a663e_idx')],
            },
        ),
        migrations.CreateModel(
            name='SuperSellerKYCSubmission',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name="Date d' ajout")),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('active', models.BooleanField(default=True, verbose_name="Désigne si l' instance est active")),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('VERIFIED', 'Vérifié'), ('REJECTED', 'Rejeté')], db_index=True, default='PENDING', max_length=20)),
                ('identity_type', models.CharField(choices=[('PASSPORT', 'Passeport'), ('ID_CARD', 'Carte d’identité'), ('DRIVER_LICENSE', 'Permis de conduire')], max_length=20)),
                ('passport_image', models.FileField(blank=True, null=True, upload_to=apps.super_sellers.models.kyc_submission.kyc_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])], verbose_name='Image Passeport')),
                ('id_front', models.FileField(blank=True, null=True, upload_to=apps.super_sellers.models.kyc_submission.kyc_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])], verbose_name='Recto')),
                ('id_back', models.FileField(blank=True, null=True, upload_to=apps.super_sellers.models.kyc_submission.kyc_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])], verbose_name='Verso')),
                ('selfie_with_document', models.FileField(blank=True, null=True, upload_to=apps.super_sellers.models.kyc_submission.kyc_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Selfie document en main')),
                ('proof_of_address', models.FileField(blank=True, null=True, upload_to=apps.super_sellers.models.kyc_submission.kyc_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])], verbose_name='Justificatif de domicile')),
                ('business_registration', models.FileField(blank=True, null=True, upload_to=apps.super_sellers.models.kyc_submission.kyc_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])], verbose_name='Registre de commerce')),
                ('additional_documents', models.JSONField(blank=True, default=list)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='super_seller_kyc_reviewed', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='super_seller_kyc_submitted', to=settings.AUTH_USER_MODEL)),
                ('super_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_submissions', to='organizations.organization')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['super_seller', 'status'], name='super_selle_super_s_401657_idx')],
            },
        ),
    ]
