# Generated by Django 5.2.1 on 2025-12-01 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_alter_eventhighlighting_end_date_and_more'),
        ('super_sellers', '0003_salesreport_salesreportpreference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerwallet',
            name='seller',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet', to='events.seller', verbose_name='Vendeur'),
        ),
        migrations.AlterField(
            model_name='sellerwithdrawal',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawals', to='events.seller', verbose_name='Vendeur'),
        ),
    ]
