# Generated by Django 5.1.1 on 2024-09-12 18:25

import apps.utils.utils.codes.utils
import apps.utils.validators
import simple_history.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOrganization',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('timestamp', models.DateTimeField(blank=True, editable=False, verbose_name="Date d' ajout")),
                ('updated', models.DateTimeField(blank=True, editable=False, verbose_name='Date de modification')),
                ('active', models.BooleanField(default=True, verbose_name="Désigne si l' instance est active")),
                ('name', models.CharField(max_length=70, verbose_name="Nom de l'organisation")),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name="Adresse mail de l'entreprise")),
                ('phone', models.CharField(default='+22900000000', max_length=25, validators=[apps.utils.validators.PhoneNumberValidator()], verbose_name='Numéro de téléphone')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name="Description de l'entreprise")),
                ('address', models.CharField(blank=True, max_length=512, null=True, verbose_name="Adresse de l'entreprise")),
                ('logo', models.TextField(blank=True, max_length=100, verbose_name="Logo de l' entreprise")),
                ('subscribe_until', models.DateField(blank=True, null=True)),
                ('phone_number_validated', models.BooleanField(default=False)),
                ('percentage', models.FloatField(default=0.3, verbose_name='Pourcentage de Wulo Events')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical organization',
                'verbose_name_plural': 'historical organizations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRole',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('timestamp', models.DateTimeField(blank=True, editable=False, verbose_name="Date d' ajout")),
                ('updated', models.DateTimeField(blank=True, editable=False, verbose_name='Date de modification')),
                ('active', models.BooleanField(default=True, verbose_name="Désigne si l' instance est active")),
                ('name', models.CharField(choices=[('Member', 'Member'), ('Coordinator', 'Coordinator')], db_index=True, max_length=150, verbose_name='Nom du role')),
                ('weight', models.PositiveBigIntegerField(choices=[(1, 'Member'), (2, 'Coordinator')], verbose_name='Poids du rôle')),
                ('description', models.CharField(max_length=512, verbose_name='Description')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Role',
                'verbose_name_plural': 'historical Roles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSubscription',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('timestamp', models.DateTimeField(blank=True, editable=False, verbose_name="Date d' ajout")),
                ('start_date', models.DateField(blank=True, verbose_name='Date de début de validité')),
                ('end_date', models.DateField(blank=True, verbose_name='Date de fin de validité')),
                ('unity_time_number', models.PositiveIntegerField(default=1, verbose_name="Nombre d' unité de temps.")),
                ('date', models.DateTimeField(blank=True, editable=False, verbose_name="Date d' activation")),
                ('updated', models.DateTimeField(blank=True, editable=False, verbose_name='Date de modification')),
                ('active_status', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Abonnement',
                'verbose_name_plural': 'historical Abonnements',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalWithdraw',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('timestamp', models.DateTimeField(blank=True, editable=False, verbose_name="Date d' ajout")),
                ('updated', models.DateTimeField(blank=True, editable=False, verbose_name='Date de modification')),
                ('active', models.BooleanField(default=True, verbose_name="Désigne si l' instance est active")),
                ('amount', models.CharField(max_length=128, verbose_name='Montant')),
                ('method', models.CharField(choices=[('MTN_BENIN', 'MTN_BENIN'), ('MOOV_BENIN', 'MOOV_BENIN')], max_length=220, verbose_name='Moyen Utilisé Pour la transaction')),
                ('disburse_token', models.CharField(blank=True, max_length=220, verbose_name='Token de retrait')),
                ('payment_phone', models.CharField(max_length=25, validators=[apps.utils.validators.PhoneNumberValidator()], verbose_name='Numéro de téléphone')),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('FAILED', 'FAILED'), ('FINISHED', 'FINISHED'), ('PROCESSING', 'PROCESSING'), ('INITIALIZED', 'INITIALIZED')], default='CREATED', max_length=120)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Paiement de Retrait',
                'verbose_name_plural': 'historical Paiements de Retraits',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name="Date d' ajout")),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('active', models.BooleanField(default=True, verbose_name="Désigne si l' instance est active")),
                ('name', models.CharField(max_length=70, verbose_name="Nom de l'organisation")),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name="Adresse mail de l'entreprise")),
                ('phone', models.CharField(default='+22900000000', max_length=25, validators=[apps.utils.validators.PhoneNumberValidator()], verbose_name='Numéro de téléphone')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name="Description de l'entreprise")),
                ('address', models.CharField(blank=True, max_length=512, null=True, verbose_name="Adresse de l'entreprise")),
                ('logo', models.ImageField(blank=True, upload_to=apps.utils.utils.codes.utils._upload_to, verbose_name="Logo de l' entreprise")),
                ('subscribe_until', models.DateField(blank=True, null=True)),
                ('phone_number_validated', models.BooleanField(default=False)),
                ('percentage', models.FloatField(default=0.3, verbose_name='Pourcentage de Wulo Events')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationFinancialAccount',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name="Date d' ajout")),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('active', models.BooleanField(default=True, verbose_name="Désigne si l' instance est active")),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Solde')),
            ],
            options={
                'verbose_name': 'Compte financier',
                'verbose_name_plural': 'Comptes financiers',
            },
        ),
        migrations.CreateModel(
            name='OrganizationFollow',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name="Date d' ajout")),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('active', models.BooleanField(default=True, verbose_name="Désigne si l' instance est active")),
            ],
            options={
                'verbose_name': "Suivi d' un organization",
                'verbose_name_plural': "Suivis d' une organization",
            },
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name="Date d' ajout")),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('active', models.BooleanField(default=True, verbose_name="Désigne si l' instance est active")),
            ],
            options={
                'verbose_name': "Membre d' une organisation",
                'verbose_name_plural': "Membres d' une organisation",
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name="Date d' ajout")),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('active', models.BooleanField(default=True, verbose_name="Désigne si l' instance est active")),
                ('name', models.CharField(choices=[('Member', 'Member'), ('Coordinator', 'Coordinator')], max_length=150, unique=True, verbose_name='Nom du role')),
                ('weight', models.PositiveBigIntegerField(choices=[(1, 'Member'), (2, 'Coordinator')], verbose_name='Poids du rôle')),
                ('description', models.CharField(max_length=512, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name="Date d' ajout")),
                ('start_date', models.DateField(blank=True, verbose_name='Date de début de validité')),
                ('end_date', models.DateField(blank=True, verbose_name='Date de fin de validité')),
                ('unity_time_number', models.PositiveIntegerField(default=1, verbose_name="Nombre d' unité de temps.")),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name="Date d' activation")),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('active_status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionType',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name="Date d' ajout")),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('active', models.BooleanField(default=True, verbose_name="Désigne si l' instance est active")),
                ('name', models.CharField(max_length=128, verbose_name='Nom')),
                ('price', models.DecimalField(decimal_places=5, default=1000.0, max_digits=15, verbose_name='Prix')),
                ('validity_days_range', models.IntegerField(blank=True, verbose_name='Nombre de jours de validité')),
                ('order', models.SmallIntegerField(default=1, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': "Type d' abonnement",
                'verbose_name_plural': "Types d' abonnements",
            },
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name="Date d' ajout")),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('active', models.BooleanField(default=True, verbose_name="Désigne si l' instance est active")),
                ('amount', models.CharField(max_length=128, verbose_name='Montant')),
                ('method', models.CharField(choices=[('MTN_BENIN', 'MTN_BENIN'), ('MOOV_BENIN', 'MOOV_BENIN')], max_length=220, verbose_name='Moyen Utilisé Pour la transaction')),
                ('disburse_token', models.CharField(blank=True, max_length=220, verbose_name='Token de retrait')),
                ('payment_phone', models.CharField(max_length=25, validators=[apps.utils.validators.PhoneNumberValidator()], verbose_name='Numéro de téléphone')),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('FAILED', 'FAILED'), ('FINISHED', 'FINISHED'), ('PROCESSING', 'PROCESSING'), ('INITIALIZED', 'INITIALIZED')], default='CREATED', max_length=120)),
            ],
            options={
                'verbose_name': 'Paiement de Retrait',
                'verbose_name_plural': 'Paiements de Retraits',
            },
        ),
    ]
