# Generated by Django 5.1.1 on 2024-10-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorganization',
            name='percentage_if_discounted',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Pourcentage de Wulo Events'),
        ),
        migrations.AddField(
            model_name='organization',
            name='percentage_if_discounted',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Pourcentage de Wulo Events'),
        ),
        migrations.AlterField(
            model_name='historicalorganization',
            name='percentage',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Pourcentage de Wulo Events'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='percentage',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Pourcentage de Wulo Events'),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=15, verbose_name='Prix'),
        ),
    ]
