# Generated by Django 5.1.7 on 2025-03-09 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_historicalorganization_percentage_if_discounted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptiontype',
            options={'ordering': ('order',), 'verbose_name': "Type d' abonnement", 'verbose_name_plural': "Types d' abonnements"},
        ),
    ]
