# Generated by Django 5.2.1 on 2025-10-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_subscriptiontype_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorganization',
            name='organization_type',
            field=models.CharField(choices=[('STANDARD', 'Organisation Standard'), ('SUPER_SELLER', 'Super-Vendeur')], db_index=True, default='STANDARD', help_text="Type d'organisation (Standard ou Super-Vendeur)", max_length=20, verbose_name="Type d'organisation"),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(choices=[('STANDARD', 'Organisation Standard'), ('SUPER_SELLER', 'Super-Vendeur')], db_index=True, default='STANDARD', help_text="Type d'organisation (Standard ou Super-Vendeur)", max_length=20, verbose_name="Type d'organisation"),
        ),
        migrations.AlterField(
            model_name='historicalrole',
            name='name',
            field=models.CharField(choices=[('Member', 'MEMBER'), ('Coordinator', 'COORDINATOR')], db_index=True, max_length=150, verbose_name='Nom du role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('Member', 'MEMBER'), ('Coordinator', 'COORDINATOR')], max_length=150, unique=True, verbose_name='Nom du role'),
        ),
    ]
