# Generated by Django 5.1.1 on 2024-10-19 12:49

import apps.notifications.models.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mobiledevice',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='notification',
            name='device_token',
        ),
        migrations.AddField(
            model_name='mobiledevice',
            name='token',
            field=models.TextField(blank=True, null=True, verbose_name="Token d' enregistrement"),
        ),
        migrations.AddField(
            model_name='notification',
            name='courier_id',
            field=models.CharField(default='user_id', max_length=1024, verbose_name='Id courier du mobile'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='data',
            field=models.JSONField(default=apps.notifications.models.utils.get_notification_default_data, verbose_name='Données'),
        ),
        migrations.AlterUniqueTogether(
            name='mobiledevice',
            unique_together={('registration_id', 'token')},
        ),
    ]
