# Generated by Django 5.1.1 on 2024-10-19 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_mobiledevice_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='courier_id',
            new_name='target_phone_id',
        ),
    ]
