# Generated by Django 5.1.1 on 2024-10-19 17:54

from django.db import migrations, transaction


@transaction.atomic
def upgrade_records(apps, schema_editor):
    NotificationModel = apps.get_model('notifications', 'Notification')
    MobileDeviceModel = apps.get_model('notifications', 'MobileDevice')

    # Perform your desired modifications here
    notifications = NotificationModel.objects.all()

    for notifications in notifications:
        if notifications.user_id:
            notifications.target_phone_id = notifications.user_id
            notifications.save(update_fields=['target_phone_id'])

    mobile_devices = MobileDeviceModel.objects.all()

    for device in mobile_devices:
        device.token = device.registration_id
        device.registration_id = device.user_id
        device.save(update_fields=['token', 'registration_id'])


class Migration(migrations.Migration):
    dependencies = [
        ('notifications', '0004_rename_courier_id_notification_target_phone_id'),
    ]

    operations = [
        migrations.RunPython(upgrade_records)
    ]
