# Generated by Django 5.1.1 on 2024-10-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_auto_20241019_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='target_phone_id',
            field=models.CharField(max_length=1024, verbose_name='Id courier du mobile'),
        ),
    ]
